### ISSUE TITLE
Enums as default values in structs fails

### ISSUE THREAD

**Issue by randyzwitch** [systemincloud/thriftr#4]
When a default value for a struct is set to an enum defined earlier in the file, there is a parsing error. In this example, field 12 refers to `TTableType table_type=TTableType.DELIMITED` and errors on the definition

```R
struct TCopyParams {
  1: string delimiter
  2: string null_str
  3: bool has_header
  4: bool quoted
  5: string quote
  6: string escape
  7: string line_delim
  8: string array_delim
  9: string array_begin
  10: string array_end
  11: i32 threads
  12: TTableType table_type=TTableType.DELIMITED
  13: string s3_access_key
  14: string s3_secret_key
  15: string s3_region
  16: TEncodingType geo_coords_encoding=TEncodingType.GEOINT
  17: i32 geo_coords_comp_param=32
  18: TDatumType geo_coords_type=TDatumType.GEOMETRY
  19: i32 geo_coords_srid=4326
  20: bool sanitize_column_names=true
}
```

```R
> mapdthrift = t_load("src/mapd.thrift")
Error in value[[3L]](cond) : Type error for field table_type at line 179
```

Source Thrift file: https://github.com/omnisci/mapd-core/blob/master/mapd.thrift

**Comment by marekjagielski** [comment]
Can you provide a small example showing this issue?

**Comment by randyzwitch** [comment]
Not sure how to provide an example, since it's part of the `t_load` step. It's things like this in the Thrift file: `TTableType table_type=TTableType.DELIMITED`

If you change the source thrift file to have the number that the enum represents, the parser works:

```
struct TCopyParams {
  1: string delimiter
  2: string null_str
  3: bool has_header
  4: bool quoted
  5: string quote
  6: string escape
  7: string line_delim
  8: string array_delim
  9: string array_begin
  10: string array_end
  11: i32 threads
  12: TTableType table_type=0   /* TTableType.DELIMITED */
  13: string s3_access_key
  14: string s3_secret_key
  15: string s3_region
  16: TEncodingType geo_coords_encoding=6   /* TEncodingType.GEOINT */
  17: i32 geo_coords_comp_param=32
  18: TDatumType geo_coords_type=18    /* TDatumType.GEOMETRY */
  19: i32 geo_coords_srid=4326
  20: bool sanitize_column_names=true
}
```
Not exactly sure how the parser/lexer is working, but I suspect that `TEncodingType.GEOINT` can't resolve to valid R code down the line (since dot syntax doesn't mean anything in R)

**Comment by marekjagielski** [comment]
Can you check this in thriftpy? This version of thriftr is based on version thriftpy 0.3.9. If it is working there, it should be easy to fix it here.

**Comment by randyzwitch** [comment]
Yes, it appears to be working on thriftpy 0.3.9

**Comment by randyzwitch** [comment]
Are you building from thriftpy or thriftpy2? thriftpy2 appears to be the maintained version now, which is now 0.3.11

**Comment by marekjagielski** [comment]
As I see this is the same source code, just the repo moved to another account. I wrote thriftr basing explicitly on 0.3.9. I will probably port changes from thriftpy 0.3.11. I guess that most of changes are python specific. Some of them  have still no counterpart in thirftr code as I miss many feature to be implemented (e.g. I support now only Binary protocol).
